print("My name is Ibrahim")
print("I am 20 years old")
print("I am in communications and electronics engineering department")
print("I will graduate in 2025 isa")
print("I love both teams but I am more interested in software because I have some experience in it")
print("Adding a slleping error to revert it :)")